[test]
timeout = 30000  # 30 seconds per test
coverageThreshold = { lines = 0.9, functions = 0.9, statements = 0.9 }
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageSkipTestFiles = true  # default false
coverageExcludeGlobs = ["__tests__", "src/modules/video-processor/events"]