services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: Dockerfile.api.dev
    environment:
      - CASSANDRA_CONTACT_POINTS=${CASSANDRA_CONTACT_POINTS}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_PUBLIC_ENDPOINT=${AWS_PUBLIC_ENDPOINT:-http://localhost:4566}
    ports:
      - "3002:3010"
    volumes:
      - ../:/usr/src/app

    depends_on:
      database:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
      localstack:
        condition: service_healthy
      localstack-init:
        condition: service_completed_successfully
    command: ["bun", "dev"]
