services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: Dockerfile.dev
    environment:
      - CASSANDRA_CONTACT_POINTS=${CASSANDRA_CONTACT_POINTS}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
    ports:
      - "3002:3010"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy
      scylla-init:
        condition: service_completed_successfully
      localstack:
        condition: service_healthy
      localstack-init:
        condition: service_completed_successfully
    command: ["bun", "dev"]
